# Generated by Django 4.1.4 on 2022-12-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('nombre_fantasia', models.CharField(max_length=150, verbose_name='Nombre de Fantasía')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='Rut')),
                ('tiendas', models.IntegerField(default=1, verbose_name='Tiendas')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('comuna', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefóno Contacto')),
                ('necesidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Necesidad')),
                ('estado', models.CharField(blank=True, choices=[('DEMO', 'DEMO'), ('ACTIVA', 'ACTIVA'), ('INHABILITADO', 'INHABILITADO')], max_length=15, null=True, verbose_name='Estado')),
                ('cuenta_demo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cuenta Demo')),
                ('fecha_inicio_demo', models.DateField(blank=True, null=True, verbose_name='Inicio Demo')),
                ('fecha_final_demo', models.DateField(blank=True, null=True, verbose_name='Fin Demo')),
                ('cuenta_opticacloud', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuenta OPTICACLOUD')),
                ('plan', models.CharField(blank=True, choices=[('MENSUAL', 'MENSUAL'), ('ANUAL', 'ANUAL')], max_length=10, null=True, verbose_name='Plan')),
                ('inicio_actividades', models.DateField(blank=True, null=True, verbose_name='Inicio de Actividades')),
                ('fin_actividades', models.DateField(blank=True, null=True, verbose_name='Fin de Actividades')),
                ('observacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observación')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('editado', models.DateTimeField(auto_now=True, verbose_name='Editado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
