# Generated by Django 4.1.4 on 2022-12-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('ENERO', 'ENERO'), ('FEBRERO', 'FEBRERO'), ('MARZO', 'MARZO'), ('ABRIL', 'ABRIL'), ('MAYO', 'MAYO'), ('JUNIO', 'JUNIO'), ('AGOSTO', 'AGOSTO'), ('SEPTIEMBRE', 'SEPTIEMBRE'), ('OCTUBRE', 'OCTUBRE'), ('NOVIEMBRE', 'NOVIEMBRE'), ('DICIEMBRE', 'DICIEMBRE')], max_length=15, verbose_name='Mes')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Tiendas')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('subtotal', models.IntegerField(verbose_name='Sub-Total')),
                ('iva_porcentaje', models.IntegerField(default=19, verbose_name='IVA(%)')),
                ('iva_total', models.IntegerField(verbose_name='IVA Total')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('n_factura', models.CharField(max_length=10, verbose_name='N° Factura (SII)')),
                ('fecha_factura', models.DateField(verbose_name='Fecha Factura (SII)')),
                ('estado', models.CharField(choices=[('DEBE', 'DEBE'), ('PAGADA', 'PAGADA'), ('ANULADA', 'ANULADA')], max_length=10, verbose_name='Estado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha Pago')),
                ('observacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observación')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('editado', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
